dataset:
  augmentation:
    homographic:
      border_reflect: true
      enable: true
      params:
        allow_artifacts: true
        corner_homography:
          enable: false
          params:
            patch_size: 128
            rho: 32
        max_angle: 1.57
        patch_ratio: 0.85
        perspective: true
        perspective_amplitude_x: 0.2
        perspective_amplitude_y: 0.2
        rotation: true
        scaling: true
        scaling_amplitude: 0.2
        translation: true
        translation_overflow: 0.05
      valid_border_margin: 0
    photometric:
      enable: false
      params:
        additive_gaussian_noise:
          stddev_range:
          - 0
          - 0.06
        additive_shade:
          kernel_size_range:
          - 50
          - 100
          transparency_range:
          - -0.5
          - 0.8
        additive_speckle_noise:
          prob_range:
          - 0
          - 0.0035
        motion_blur:
          max_kernel_size: 3
        random_brightness:
          max_abs_change: 0.15
        random_contrast:
          strength_range:
          - 0.3
          - 1.8
      primitives:
      - random_brightness
      - random_contrast
      - additive_speckle_noise
      - additive_gaussian_noise
      - additive_shade
      - motion_blur
  filename: /home/wasproject/Desktop/Can/DATASETS/hdf5_DATASETS/dataset_files/MULTIPOINT/training.hdf5
  height: 256
  keypoints_filename: /home/wasproject/Desktop/Can/DATASETS/hdf5_DATASETS/keypoint_files/RIFT2/rift2.hdf5
  random_pairs: false
  single_image: false
  type: ImagePairDataset
  width: 256
loss:
  descriptor_loss: true
  descriptor_loss_threshold: 4.0
  descriptor_loss_use_mask: true
  detector_dustbin_loss_weight: 0.025
  detector_focal_loss:
    alpha: 0.25
    gamma: 2.0
    reduction: mean
    use: false
  detector_handle_multiple_keypoints: soft_assignment
  detector_loss: true
  detector_loss_function: cross_entropy
  detector_use_cross_entropy: true
  homography_regression_loss:
    check: true
    gamma: 1.0
  lambda: 1.0
  lambda_d: 250
  negative_margin: 0.2
  positive_margin: 1.0
  sparse_descriptor_loss: false
  sparse_descriptor_loss_num_cell_divisor: 64
  type: XPointLoss
  use_encoder_similarity: false
model:
  bn_first: false
  descriptor_head: true
  descriptor_size: 256
  final_batchnorm: true
  homography_regression_head:
    check: true
    type: RegNet
  intepolation_mode: bilinear
  mixed_precision: true
  multispectral: false
  normalize_descriptors: true
  reflection_pad: true
  takes_pair: true
  type: XPoint
  use_attention:
    check: true
    height: 256
    model_parameters:
      DATA:
        IMG_SIZE: 512
      MODEL:
        DROP_PATH_RATE: 0.2
        NAME: vssm_tiny_segmentation
        TYPE: vssm
        VSSM:
          DEPTHS:
          - 2
          - 2
          - 2
          - 2
          DOWNSAMPLE: v3
          EMBED_DIM: 96
          MLP_RATIO: 4.0
          PATCHEMBED: v2
          SSM_CONV: 3
          SSM_CONV_BIAS: false
          SSM_DT_RANK: auto
          SSM_D_STATE: 1
          SSM_FORWARDTYPE: v05_noz
          SSM_RATIO: 1.0
    pretrained:
      check: true
      type_dir: /home/wasproject/Desktop/Can/XPoint/model_weights/encoder-pretrained/vmamba-imagenet/vssm_tiny_segmentation_special/
      yaml_file: /home/wasproject/Desktop/Can/XPoint/model_weights/encoder-pretrained/vmamba-imagenet/vssm_tiny_segmentation_special/vssm_tiny.yaml
    type: VMamba
    width: 256
training:
  allow_gpu: true
  batchsize: 16
  learningrate: 1e-4
  mixed_precision: true
  n_epochs: 3000
  num_worker: 8
  output_directory: model_weights/XPoint-EXP1
  save_every_n_epoch: 20
  scheduler:
    gamma: 0.89
    step_size: 2
    type: ExponentialLR
    use_scheduler: false
  use_writer: true
  validation:
    compute_validation_loss: false
  weight_decay: 0
