dataset:
    type: 'ImagePairDataset'
    filename: /home/wasproject/Desktop/Can/DATASETS/hdf5_DATASETS/dataset_files/MULTIPOINT/training.hdf5 #data/training.hdf5
    keypoints_filename: /home/wasproject/Desktop/Can/DATASETS/hdf5_DATASETS/keypoint_files/RIFT2/rift2.hdf5 #tmp/RIFT2/rift2.hdf5
    single_image: false #LOOK
    random_pairs: false #LOOK
    height: &height 256 # LOOK
    width: &width  256 # LOOK
    augmentation:
        photometric:
            enable: false #default is true however photoetric applied phased images doesn't make sense
            primitives: [
                'random_brightness', 'random_contrast', 'additive_speckle_noise',
                'additive_gaussian_noise', 'additive_shade', 'motion_blur' ]
            params:
                random_brightness: {max_abs_change: 0.15}
                random_contrast: {strength_range: [0.3, 1.8]}
                additive_gaussian_noise: {stddev_range: [0, 0.06]}
                additive_speckle_noise: {prob_range: [0, 0.0035]}
                additive_shade:
                    transparency_range: [-0.5, 0.8]
                    kernel_size_range: [50, 100]
                motion_blur: {max_kernel_size: 3}
        homographic:
            enable: true #LOOK
            params:
                corner_homography: #ADDED BY ME
                    enable: false #LOOK
                    params:
                        patch_size : 128
                        rho: 32
                translation: true
                rotation: true
                scaling: true
                perspective: true
                scaling_amplitude: 0.2 #0.2
                perspective_amplitude_x: 0.2 #0.2
                perspective_amplitude_y: 0.2 #0.2
                patch_ratio: 0.85 #0.85
                max_angle: 1.57  # 3.14
                allow_artifacts: true
                translation_overflow: 0.05 #0.05
            valid_border_margin: 0
            border_reflect: true

model:
    type: 'XPoint' #LOOK SwinMultiPoint
    multispectral: false #LOOK
    descriptor_head: true
    descriptor_size: 256 #64
    intepolation_mode: bilinear
    normalize_descriptors: true
    final_batchnorm: true
    reflection_pad: true
    bn_first: false
    mixed_precision: true #?? it was false
    homography_regression_head : #added by me
        check : &homography_regression true #LOOK
        type : 'RegNet' #SRHENNet, HomographyNet
    takes_pair: true #LOOK
    use_attention :
        check : true #LOOK
        type : 'VMamba' #'VMamba' #'ScuNet' #
        height : *height
        width : *width
        pretrained :
            check : true #LOOK
            type_dir : /home/wasproject/Desktop/Can/XPoint/model_weights/encoder-pretrained/vmamba-imagenet/vssm_tiny_segmentation_special/ #"../xpoint-beta/model_weights/swinv2-imagenet/tiny256-w8-special" #large384 #LOOK


loss:
    type: 'XPointLoss'
    detector_loss: true
    detector_use_cross_entropy: true
    descriptor_loss: true
    descriptor_loss_threshold: 4.0
    descriptor_loss_use_mask: true
    sparse_descriptor_loss: false
    sparse_descriptor_loss_num_cell_divisor: 64
    positive_margin: 1.0
    negative_margin: 0.2
    lambda_d: 250
    lambda: 1.0
    use_encoder_similarity: false #LOOK
    homography_regression_loss: #added by me
        check : *homography_regression #LOOK
        gamma : 1.0
    detector_loss_function: 'cross_entropy'  # Options: 'cross_entropy', 'binary_cross_entropy', 'focal_loss'
    detector_handle_multiple_keypoints: 'soft_assignment'  # Options: 'hard_assignment', 'soft_assignment', 'multi_class'
    detector_dustbin_loss_weight: 0.025
    detector_focal_loss: 
        use: False  # Whether to use Focal Loss
        alpha: 0.25 # Focal Loss alpha parameter
        gamma: 2.0   # Focal Loss gamma parameter
        reduction: 'mean' # Focal Loss reduction method

training:
    mixed_precision : true
    n_epochs: 3000 #3000
    learningrate: 1e-4 #1e-4
    scheduler: 
        use_scheduler: false
        type: 'ExponentialLR'
        step_size: 2
        gamma: 0.89
    weight_decay: 0 #5e-4
    batchsize: 16 # 16
    num_worker: 8 #4 before but 0 is good practice for ddp
    allow_gpu: true
    use_writer: true
    output_directory: model_weights/XPoint-EXP1  #'model_weights/swinv2-tiny-w16-256 LOOK
    save_every_n_epoch: 20
    validation:
        compute_validation_loss: false

